import Head from 'next/head';
// import { Inter } from 'next/font/google';
// import styles from '@/styles/Home.module.css';
import styles from './Home.module.css';

import MyApiCallInNextPage from './MyApiCallInNextPage';
import axios from 'axios';
import { GetStaticProps } from 'next';

type Repo = {
  name: string;
  stargazers_count: number;
};

export const getStaticProps: GetStaticProps<{
  repo: Repo;
}> = async () => {
  const res = await fetch('https://api.github.com/repos/vercel/next.js');
  const repo = await res.json();
  console.log(repo);
  return { props: { repo } };
};

function onSubmit() {
  axios
    .post('https://jsonplaceholder.typicode.com/users')
    .then(function (response) {
      //setDatas(response.data);
      console.log(response);
      alert('success post request' + response);
      alert('success post request' + JSON.stringify(response.data));
      alert('success post request' + JSON.parse(response.data));
    })
    .catch(function (error) {
      console.log(error);
    });
}

// const inter = Inter({ subsets: ['latin'] });
const Home = (): JSX.Element => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://unpkg.com/primeflex@^3/primeflex.css" />
        <link rel="stylesheet" href="https://unpkg.com/primeflex/themes/saga-blue.css" />
        <link rel="stylesheet" href="https://unpkg.com/primeflex/themes/arya-blue.css" />
        <link rel="stylesheet" href="https://unpkg.com/primeflex/themes/vela-blue.css" />
        {/* // eslint-disable-next-line @next/next/no-sync-scripts
        <script
          src="https://cdn.jsdelivr.net/npm/react/umd/react.production.min.js"
          crossOrigin
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/react-dom/umd/react-dom.production.min.js"
          crossorigin
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/react-bootstrap@next/dist/react-bootstrap.min.js"
          crossorigin
        ></script>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
          crossorigin="anonymous"
        /> */}
      </Head>
      <main className={styles.main}>
        <button type="button" className="color:red" onClick={onSubmit}>
          PostRequest
        </button>
        <div className={styles.grid}>
          <MyApiCallInNextPage />
        </div>
      </main>
    </>
  );
};
export default Home;
